quarkus:
  banner:
    path: banner.txt

  http:
    port: 8020
    root-path: /
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: admin
    password: admin217

    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus_db
      min-size: 4
      max-size: 16

  mybatis:
    environment: dev
    xmlconfig:
      enable: true

  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    schemas: public

  swagger-ui:
    enable: true

  native:
    resources:
      includes:
        publicKey.pem

smallrye:
    jwt:
      sign:
        key:
          location:
             privateKey.pem
      encrypt:
        key: publicKey.pem

mp:
  jwt:
    verify:
      publickey:
        location:
          publicKey.pem
  messaging:
      outgoing:
        person-sink:
          connector: smallrye-kafka
          bootstrap:
           servers: localhost:9092

        id-sink:
          connector: smallrye-kafka
          topic: idtopic

      incoming:
        persontopic:
          connector: smallrye-kafka
          bootstrap:
            servers: localhost:9092

        idtopic:
          connector: smallrye-kafka
          bootstrap:
            servers: localhost:9092

camel:
  openapi:
    expose:
      enabled: true


"%prod":
  quarkus:
    mongodb:
      connection-string:  mongodb://admin:admin217@localhost:27017

    devservices:
      enabled: false


"%test":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost:5433/quarkus_db
      devservices:
        enabled: true
        image-name: postgres
        db-name: quarkus_db
        port: 5433

    mybatis:
      environment: test

    mongodb:
       devservices:
         enabled: true
         image-name: mongo
         port: 27017


    devservices:
      enabled: true
    http:
      port: 8010
