quarkus:
  banner:
    path: banner.txt

  http:
    port: 8020
    test-port: 8010

  datasource:
    db-kind: postgresql
    username: admin
    password: admin217

    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus_db
      min-size: 4
      max-size: 16

  mybatis:
    environment: dev
    xmlconfig:
      enable: true

  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    schemas: public


      #    test:
#      jdbc:
#          url: jdbc:postgresql://localhost:5432/quarkus_test
#      min-size: 4
#      max-size: 16




#  mongodb:
#    connection-string:  mongodb://admin:admin217@localhost:27017

  swagger-ui:
    always-include: true


  smallrye-jwt:
    enabled: true
    jwt:
      sign:
        key-location: publicKey.pem

  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: https://quarkus.io/using-jwt-rbac

#mp:
#  messaging:
#    outgoing:
#      person-sink:
#        connector: smallrye-kafka
#        topic: persontopic
#        value:
#          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#
#      id-sink:
#        connector: smallrye-kafka
#        topic: idtopic
#        value:
#          serializer: org.apache.kafka.common.serialization.LongSerializer
#
#    incoming:
#      persontopic:
#        connector: smallrye-kafka
#        topic: persontopic
#        value:
#           deserializer: org.abondar.experimental.quarkusdemo.model.PersonDeserializer
#
#      idtopic:
#        connector: smallrye-kafka
#        topic: idtopic
#        value:
#          deserializer: org.apache.kafka.common.serialization.LongDeserializer


#camel:
#  context:
#    name: quarkus-demo-context


vertx:
  prefer-native-transport: true


"%test":
  quarkus:
    datasource:
      jdbc:
       url: jdbc:postgresql://localhost:5432/quarkus_test
    mybatis:
      environment: test
