quarkus:
  banner:
    path: banner.txt

  http:
    port: 8020
    test-port: 8010

  datasource:
    db-kind: postgresql
    username: admin
    password: admin217

    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus_db
      min-size: 4
      max-size: 16

    test:
      jdbc:
          url: jdbc:postgresql://localhost:5432/quarkus_test
      min-size: 4
      max-size: 16

  mybatis:
    xmlconfig:
      enable: true
      path: configuration.xml

  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    schemas: public


  mongodb:
    connection-string:  mongodb://admin:admin217@localhost:27017

  swagger-ui:
    always-include: true


  smallrye-jwt:
    enabled: true
mp:
  messaging:
    outgoing:
      person-sink:
        connector: smallrye-kafka
        topic: persontopic
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

      id-sink:
        connector: smallrye-kafka
        topic: idtopic
        value:
          serializer: org.apache.kafka.common.serialization.LongSerializer

    incoming:
      persontopic:
        connector: smallrye-kafka
        topic: persontopic
        value:
           deserializer: org.abondar.experimental.quarkusdemo.model.PersonDeserializer

      idtopic:
        connector: smallrye-kafka
        topic: idtopic
        value:
          deserializer: org.apache.kafka.common.serialization.LongDeserializer

  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: https://quarkus.io/using-jwt-rbac

camel:
  context:
    name: quarkus-demo-context


vertx:
  prefer-native-transport: true

smallrye:
  jwt:
    sign:
      key-location: publicKey.pem
