quarkus:
  banner:
    path: banner.txt

  http:
    port: 8020
    root-path: /
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: admin
    password: admin217

    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus_db
      min-size: 4
      max-size: 16

  mybatis:
    environment: dev
    xmlconfig:
      enable: true

  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    schemas: public

  swagger-ui:
    always-include: true

  smallrye-jwt:
    enabled: true
    jwt:
      sign:
        key-location: publicKey.pem

  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: https://quarkus.io/using-jwt-rbac

#mp:
#  messaging:
#    outgoing:
#      person-sink:
#        connector: smallrye-kafka
#        topic: persontopic
#        value:
#          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#
#      id-sink:
#        connector: smallrye-kafka
#        topic: idtopic
#        value:
#          serializer: org.apache.kafka.common.serialization.LongSerializer
#
#    incoming:
#      persontopic:
#        connector: smallrye-kafka
#        topic: persontopic
#        value:
#           deserializer: org.abondar.experimental.quarkusdemo.model.PersonDeserializer
#
#      idtopic:
#        connector: smallrye-kafka
#        topic: idtopic
#        value:
#          deserializer: org.apache.kafka.common.serialization.LongDeserializer


#camel:
#  context:
#    name: quarkus-demo-context


vertx:
  prefer-native-transport: true

"%prod":
  quarkus:
    mongodb:
      connection-string:  mongodb://admin:admin217@localhost:27017

    devservices:
      enabled: false


"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: postgres
        db-name: quarkus_db
        port: 5432

    mybatis:
      environment: test

    mongodb:
       devservices:
         enabled: true
         image-name: mongo
         port: 27017


    devservices:
      enabled: true
    http:
      port: 8010
